name: run_tox
runs:
  using: composite
  steps:
  - name: Run tox
    env:
      AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
      AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
      AWS_EC2_PEM: "github-test-farm.pem"
      PIP_USE_PEP517: "${{ matrix.PIP_USE_PEP517 }}"
      TOXENV: "${{ matrix.TOXENV }}"
    run: |-
      set -e
      export TARGET_BRANCH="`echo "${BUILD_SOURCEBRANCH}" | sed -E 's!refs/(heads|tags)/!!g'`"
      [ -z "${SYSTEM_PULLREQUEST_TARGETBRANCH}" ] || export TARGET_BRANCH="${SYSTEM_PULLREQUEST_TARGETBRANCH}"
      env
      python3 -m tox run
    shell: bash
