#!/bin/sh -e

# get certbot version
cb_installed=$(grep -oP 'installed:\s+\K\d+.\d+.\d(?=-)' $SNAP/certbot-version/certbot)
# get required certbot version for plugin
cb_required=$(grep -oP "certbot>=\K.*(?=')" $SNAP/setup.py)

If [ "$cb_installed" -lt "$cb_required" ]; then
    echo "Certbot needs to be updated before this plugin can be updated; will try again on next refresh."
    exit 1
fi
