#!/bin/sh -e

# get certbot version
cb_installed="$(snapctl get cb-installed)"

if [ -z "$cb_installed" ]; then
    echo "cb_installed not set, not doing version comparison check" > "$SNAP_DATA/debuglog"
    exit 0
fi

echo "cb_installed: $cb_installed"

# get required certbot version for plugin
cb_required=$(grep -oP "certbot>=\K.*(?=')" $SNAP/setup.py)
echo "cb_required: $cb_required" > "$SNAP_DATA/debuglog"

if [ "$cb_installed" -lt "$cb_required" ]; then
    echo "Certbot is version $cb_installed but needs to be at least $cb_required before \
    this plugin can be updated; will try again on next refresh."
    exit 1
fi
