#!/bin/sh -e

# get certbot version
cb_installed="$(snapctl get cb-installed)"

if [ -z "$cb_installed" ]; then
    echo "cb_installed not set, not doing version comparison check"
    exit 0
fi

# get required certbot version for plugin
cb_required=$(grep -oP "certbot>=\K.*(?=')" $SNAP/setup.py)

if [ "$cb_installed" -lt "$cb_required" ]; then
    echo "Certbot is version $cb_installed but needs to be at least $cb_required before \
    this plugin can be updated; will try again on next refresh."
    exit 1
fi
