#!/bin/sh -e

first_install="$(snapctl get first-install)"
if [ -z "$first_install" ]; then
    snapctl set first-install="false"
    echo "first install, not doing any version comparison checks"
    exit 0
fi

echo "ls $SNAP/certbot-exec:"
ls $SNAP/certbot-exec
cb_installed=$(grep -oP "__requires__ = 'certbot==\K.*(?=')" $SNAP/certbot-exec)
echo "cb_installed: $cb_installed"
snapctl set cb-installed="$cb_installed"
