# Configuration for https://github.com/marketplace/stale

# Number of days of inactivity before an Issue or Pull Request becomes stale
daysUntilStale: 365

# Number of days of inactivity before an Issue or Pull Request with the stale label is closed.
# Set to false to disable. If disabled, issues still need to be closed manually, but will remain marked as stale.
# When changing this value, be sure to also update markComment below.
daysUntilClose: 30

# Ignore issues with an assignee (defaults to false)
exemptAssignees: true

# Label to use when marking as stale
staleLabel: needs-update

# Comment to post when marking as stale. Set to `false` to disable
markComment: >
  We've made a lot of changes to Certbot since this issue was opened. If you
  still have this issue with an up-to-date version of Certbot, can you please
  add a comment letting us know? This helps us to better see what issues are
  still affecting our users. If there is no activity in the next 30 days, this
  issue will be automatically closed.

# Comment to post when closing a stale Issue or Pull Request.
closeComment: >
  This issue has been closed due to lack of activity, but if you think it
  should be reopened, please open a new issue with a link to this one and we'll
  take a look.

# Limit the number of actions per hour, from 1-30. Default is 30
limitPerRun: 1

# Don't mark pull requests as stale.
only: issues
