coverage:
  status:
    project:
      default: off
      linux:
        flags: linux
        # Fixed target instead of auto set by #7173, can
        # be removed when flags in Codecov are added back.
        target: 97.6
        threshold: 0.1
        base: auto
      windows:
        flags: windows
        # Fixed target instead of auto set by #7173, can
        # be removed when flags in Codecov are added back.
        target: 97.1
        threshold: 0.1
        base: auto
