timeout: 3600s
steps:
- id: certbot
  name: 'gcr.io/cloud-builders/docker'
  args: ["build", "-t", "us.gcr.io/$PROJECT_ID/certbot:latest", "."]
  dir: .
  waitFor: ['-']

- name: 'gcr.io/cloud-builders/docker'
  args: ["build", "-t", "us.gcr.io/$PROJECT_ID/certbot-dns-google:latest", "."]
  dir: certbot-dns-google
  waitFor:
    - certbot

images:
  - us.gcr.io/$PROJECT_ID/certbot
  - us.gcr.io/$PROJECT_ID/certbot-dns-google

logsBucket: fathom-containers-cloud-build-logs-36tugmiz
