# This Dockerfile builds an image for development.
FROM debian:buster

# Note: this only exposes the port to other docker containers.
EXPOSE 80 443

WORKDIR /opt/certbot/src

COPY . .
RUN apt-get update && \
    apt-get install apache2 git python3-dev python3-venv gcc libaugeas0 \
                    libssl-dev libffi-dev ca-certificates openssl nginx-light -y && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* \
           /tmp/* \
           /var/tmp/*

RUN VENV_NAME="../venv3" python3 tools/venv3.py

ENV PATH /opt/certbot/venv3/bin:$PATH
