# This Dockerfile builds an image for development.
FROM ubuntu:focal

# Note: this only exposes the port to other docker containers.
EXPOSE 80 443

WORKDIR /opt/certbot/src

COPY . .
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install apache2 git python3-dev \
        python3-venv gcc libaugeas0 libssl-dev libffi-dev ca-certificates \
        openssl nginx-light pkg-config -y --no-install-recommends && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* \
           /tmp/* \
           /var/tmp/*

RUN VENV_NAME="../venv" python3 tools/venv.py

ENV PATH /opt/certbot/venv/bin:$PATH
