#!/bin/bash
set -ex

WORK_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
source "$WORK_DIR/../../lib/common"

CERTBOT_VERSION=$(GetCerbotVersionFromTag "$DOCKER_TAG")

for TARGET_ARCH in "${ALL_TARGET_ARCH[@]}"; do
    PushDockerImage "${TARGET_ARCH}" "${CERTBOT_VERSION}"
done
