name: setup_tox
runs:
  using: composite
  steps:
  - name: Install MacOS dependencies
    if: startsWith(matrix.IMAGE_NAME, 'macOS')
    run: |-
      set -e
      unset HOMEBREW_NO_INSTALL_FROM_API
      brew untap homebrew/core homebrew/cask
      brew update
      brew install augeas
    shell: bash
  - name: Install Linux dependencies
    if: startsWith(matrix.IMAGE_NAME, 'ubuntu')
    run: |-
      set -e
      sudo apt-get update
      sudo apt-get install -y --no-install-recommends \
        libaugeas-dev \
        nginx-light
      sudo systemctl stop nginx
      sudo sysctl net.ipv4.ip_unprivileged_port_start=0
    shell: bash
  - uses: actions/setup-python@v5.0.0
    with:
      python-version: "${{ matrix.PYTHON_VERSION }}"
  - name: Install runtime dependencies
    run: |-
      set -e
      python3 tools/pip_install.py tox
    shell: bash
  - name: Create test farm pem file
    if: contains(matrix.TOXENV, 'test-farm')
    env:
      PEM_CONTENTS: "${{ secrets.AWS_TEST_FARM_PEM }}"
    run: 'echo ${PEM_CONTENTS} >> github-test-farm.pem'
    shell: bash
