jobs:
  - job: doc_test
    strategy:
      matrix:
        acme:
          folder_path: acme
        certbot:
          folder_path: certbot
        cloudflare:
          folder_path: certbot-dns-cloudflare
        cloudxns:
          folder_path: certbot-dns-cloudxns
        digitalocean:
          folder_path: certbot-dns-digitalocean
        dnsimple:
          folder_path: certbot-dns-dnsimple
        dnsmadeeasy:
          folder_path: certbot-dns-dnsmadeeasy
        gehim:
          folder_path: certbot-dns-gehim
        google:
          folder_path: certbot-dns-google
        linode:
          folder_path: certbot-dns-linode
        luadns:
          folder_path: certbot-dns-luadns
        nsone:
          folder_path: certbot-dns-nsone
        ovh:
          folder_path: certbot-dns-ovh
        rfc2136:
          folder_path: certbot-dns-rfc2136
        route53:
          folder_path: certbot-dns-route53
        sakuracloud:
          folder_path: certbot-dns-sakuracloud
    pool:
      vmImage: ubuntu-latest
    
    steps:
      - bash: |
          set -e
          python3 -m venv venv
          venv/bin/python tools/pipstrap.py
          venv/bin/python tools/pip_install_editable.py $(folder_path)[docs]
          venv/bin/python sphinx-build -W -b html ./$(folder_path)/docs _build
