jobs:
  - job: doc_test
    strategy:
      matrix:
        acme:
          folder_path: acme
        certbot:
          folder_path: certbot
        dns_cloudflare:
          folder_path: certbot-dns-cloudflare
        dns_cloudxns:
          folder_path: certbot-dns-cloudxns
        dns_digitalocean:
          folder_path: certbot-dns-digitalocean
        dns_dnsimple:
          folder_path: certbot-dns-dnsimple
        dns_dnsmadeeasy:
          folder_path: certbot-dns-dnsmadeeasy
        dns_gehirn:
          folder_path: certbot-dns-gehirn
        dns_google:
          folder_path: certbot-dns-google
        dns_linode:
          folder_path: certbot-dns-linode
        dns_luadns:
          folder_path: certbot-dns-luadns
        dns_nsone:
          folder_path: certbot-dns-nsone
        dns_ovh:
          folder_path: certbot-dns-ovh
        dns_rfc2136:
          folder_path: certbot-dns-rfc2136
        dns_route53:
          folder_path: certbot-dns-route53
        dns_sakuracloud:
          folder_path: certbot-dns-sakuracloud
    pool:
      vmImage: ubuntu-latest
    
    steps:
      - bash: |
          set -e
          python3 -m venv .venv
          source .venv/bin/activate
          python tools/pipstrap.py
          python tools/pip_install_editable.py $(folder_path)[docs]
          sphinx-build -W -b html ./$(folder_path)/docs _build
        displayName: Build Sphinx Documentation