stages:
  - stage: Notify
    condition: succeededOrFailed()
    jobs:
      - job: notify_release_finished
        pool:
          vmImage: ubuntu-latest
        steps:
          - bash: |
              set -e
              python -m venv venv
              source venv/bin/activate
              tools/pip_install.py requests
              "${BUILD_REPOSITORY_LOCALPATH}/tools/notify_mattermost.py"
            displayName: Send mattermost message
