stages:
  - stage: Notify
    jobs:
      - job: notify release build success
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: DownloadSecureFile@1
            name: webhook_url
            inputs:
              secureFile: mattermost_webhook_url_release_success
          - bash: |
              set -e
              AUTHOR_NAME="$(git log -1 --pretty=format:'%an')"
              "${BUILD_REPOSITORY_LOCALPATH}/tools/notify_mattermost.py" "${AUTHOR_NAME}" $(webhook_url.secureFilePath)
            displayName: Send mattermost message
