.TH "LETSENCRYPT" "1" 
.SH "NAME" 
letsencrypt \(em An ACME client that can update Apache configurations
.SH "SYNOPSIS" 
.PP 
\fBletsencrypt\fR [\fB-d\fP \fIdomain\fR [\fIdomain\fR ...]] [\fB-s\fP \fIserver\fR] [\fB-p\fP \fIprivkey\fR] [\fB-c\fP \fIcsr\fR] [\fB-r\fP] [\fB-n\fP] [\fB-e\fP] [\fB-t\fP] [\fB--test\fP]

.SH "DESCRIPTION" 
.PP 
The objective of Let’s Encrypt and the ACME (Automated Certificate
Management Environment) protocol is to make it possible to set up an HTTPS
server and have it automatically obtain a browser-trusted certificate,
without any human intervention. This is accomplished by running the
\fBletsencrypt\fR certificate management agent on the web server.
.SH "OPTIONS" 
.PP 
This program follows the usual GNU command line syntax, 
with long options starting with two dashes (`\-').  A summary of 
options is included below.

.IP "\fB-h\fP, \fB\-\-help\fP"
Show summary of options. 

.IP "\fB-d\fP \fIdomain\fR [\fIdomain ...\fR], \fB\-\-domains\fP \fIdomain\fR [\fIdomain ...\fR]"

.IP "\fB-s\fP \fIserver\fR, \fB\-\-server\fP \fIserver\fR"
The ACME CA server address.

.IP "\fB-p\fP \fIprivkey\fR, \fB\-\-privkey\fP \fIprivkey\fR"
Path to the private key file for certificate generation.

.IP "\fB-c\fP \fIcsr\fR, \fB\-\-csr\fP \fIcsr\fR"
Path to the certificate signing request file corresponding to the private
key file. The private key file argument is required if this argument is
specified.

.IP "\fB-b\fP \fIN\fR, \fB\-\-rollback\fP \fIN\fR"
Revert configuration N number of checkpoints.

.IP "\fB-k\fP, \fB\-\-revoke\fP"
Revoke a certificate.

.IP "\fB-v\fP, \fB\-\-view-checkpoints\fP"
View checkpoints and associated configuration changes.

.IP "\fB-r\fP, \fB\-\-redirect\fP"
Automatically redirect all HTTP traffic to HTTPS for the newly authenticated
vhost.

.IP "\fB-n\fP, \fB\-\-no-redirect\fP"
Skip the HTTPS redirect question, allowing both HTTP and HTTPS.

.IP "\fB-e\fP, \fB\-\-agree-eula\fP"
Skip the end user license agreement screen.

.IP "\fB-t\fP, \fB\-\-text\fP"
Use the text output instead of the curses UI.

.IP "\fB\-\-test\fP"
Run in test mode.

.SH "AUTHOR" 
.PP 
This manual page was written by Francois Marier <francois@debian.org> for 
the \fBDebian\fP system (but may be used by others).  Permission is 
granted to copy, distribute and/or modify this document under 
the terms of the Apache License, Version 2.0.
.PP 
On Debian systems, the complete text of the Apache License Version 2.0
can be found in /usr/share/common-licenses/Apache-2.0 .
