#!/bin/bash

# A hackish script to see if the client is behaving as expected 
# with each of the "passing" conf files.

# TODO presently this requires interaction and human judgement to 
# assess, but it should be automated
export EA=/etc/apache2/ 
TESTDIR="`dirname $0`"
LEROOT="`realpath \"$TESTDIR/../../\"`"
cd $TESTDIR/passing

function CleanupExit() {
    echo control c, exiting tests...
    if [ "$f" != "" ] ; then
        sudo rm /etc/apache2/sites-{enabled,available}/"$f"
    fi
    exit 1
}

FAILS=0
trap CleanupExit INT
for f in *.conf ; do 
    echo -n  testing "$f"...
    sudo cp "$f" "$EA"/sites-available/
    sudo ln -s "$EA/sites-available/$f" "$EA/sites-enabled/$f"
    RESULT=`echo c | sudo "$LEROOT"/venv/bin/letsencrypt --apache --register-unsafely-without-email --agree-tos certonly -t 2>&1`
    if echo $RESULT | grep -Eq \("Please specify --domains"\|"mod_macro is not yet"\) ; then
        echo passed
    else
        echo failed
        echo $RESULT
        echo
        echo
        FAILS=`expr $FAILS + 1`
    fi
    sudo rm /etc/apache2/sites-{enabled,available}/"$f"
done
if [ "$FAILS" -ne 0 ] ; then
    return 1
fi
return 0
