#!/bin/bash

# A hackish script to see if the client is behaving as expected 
# with each of the "passing" conf files.

# TODO presently this requires interaction and human judgement to 
# assess, but it should be automated
export EA=/etc/apache2/ 
TESTDIR="`dirname $0`"
LEROOT="`realpath \"$TESTDIR/../../\"`"
cd $TESTDIR/passing
LETSENCRYPT="${LETSENCRYPT:-$LEROOT/venv/bin/letsencrypt}"

function CleanupExit() {
    echo control c, exiting tests...
    if [ "$f" != "" ] ; then
        sudo rm /etc/apache2/sites-{enabled,available}/"$f"
    fi
    exit 1
}

FAILS=0
trap CleanupExit INT
for f in *.conf ; do 
    echo -n  testing "$f"...
    if [ "$APPEND_APACHECONF" = "" ] ; then
        sudo cp "$f" "$EA"/sites-available/
        sudo ln -sf "$EA/sites-available/$f" "$EA/sites-enabled/$f"
    else
        TMP="/tmp/`basename \"$APPEND_APACHECONF\"`.$$"
        sudo cp -a "$APPEND_APACHECONF" "$TMP"
        sudo bash -c "cat \"$f\" >> \"$APPEND_APACHECONF\""
    fi
    RESULT=`echo c | sudo "$LETSENCRYPT" --staging --apache --register-unsafely-without-email --agree-tos certonly -t 2>&1`
    if echo $RESULT | grep -Eq \("Please specify --domains"\|"mod_macro is not yet"\) ; then
        echo passed
    else
        echo failed
        echo $RESULT
        echo
        echo
        FAILS=`expr $FAILS + 1`
    fi
    if [ "$APPEND_APACHECONF" = "" ] ; then
        sudo rm /etc/apache2/sites-{enabled,available}/"$f"
    else
        sudo mv "$TMP" "$APPEND_APACHECONF"
    fi
done
if [ "$FAILS" -ne 0 ] ; then
    exit 1
fi
exit 0
