#!/bin/bash
set -euo pipefail

WORK_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
REPO_ROOT="$(dirname "$(dirname "${WORK_DIR}")")"
REQUIREMENTS_FILE="$REPO_ROOT/tools/requirements.txt"
RELATIVE_SCRIPT_PATH="$(realpath --relative-to "$REPO_ROOT" "$WORK_DIR")/$(basename "${BASH_SOURCE[0]}")"

if ! command -v poetry >/dev/null || ! command -v hashin >/dev/null; then
    echo "Please install poetry and hashin."
    echo "You may need to recreate Certbot's virtual environment and activate it."
    exit 1
fi

cd "${WORK_DIR}"

if [ -f poetry.lock ]; then
    rm poetry.lock
fi

poetry lock

TEMP_REQUIREMENTS=$(mktemp)
trap 'rm $TEMP_REQUIREMENTS' EXIT

poetry export -o "${TEMP_REQUIREMENTS}"
# We need to remove local packages from the requirements file.
sed -i '/^acme @/d; /certbot/d;' "${TEMP_REQUIREMENTS}"
# Poetry currently will not include these packages in lockfiles or requirements
# files. See https://github.com/python-poetry/poetry/issues/1584 which should
# hopefully be resolved soon by
# https://github.com/python-poetry/poetry/pull/2826. To work around this for
# now, we use hashin. We currently require an older version of pip without real
# dependency resolution due to our "oldest" tests.
hashin -r "${TEMP_REQUIREMENTS}" pip==20.2.4 setuptools wheel

cat << EOF > "$REQUIREMENTS_FILE"
# This file was generated by $RELATIVE_SCRIPT_PATH.
#
# It is normally used as constraints to pip, however, it has the name
# requirements.txt so that is scanned by GitHub. See
# https://docs.github.com/en/github/visualizing-repository-data-with-graphs/about-the-dependency-graph#supported-package-ecosystems
# for more info.
EOF
cat "${TEMP_REQUIREMENTS}" >> "${REQUIREMENTS_FILE}"
