# Advanced pipeline for running our full test suite on demand.
name: Full test suite
on:
  push:
    branches:
    # When changing these triggers, please ensure the documentation under
    # "Running tests in CI" is still correct.
    - test-*
  workflow_dispatch:
permissions:
  contents: read

jobs:
  # These four jobs could be grouped in a separate workflow, but the github actions UI
  # is much nicer if they are instead listed explicitly here.
  standard_tests_jobs:
    name: Standard tests
    uses: "./.github/workflows/standard_tests_jobs.yml"
  extended_tests_jobs:
    name: Extended tests
    uses: "./.github/workflows/extended_tests_jobs.yml"
    secrets:
      AWS_TEST_FARM_PEM: "${{ secrets.AWS_TEST_FARM_PEM }}"
      AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
      AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
  docker_packaging_jobs:
    name: Docker packaging
    uses: "./.github/workflows/docker_packaging_jobs.yml"
    with:
      # We don't publish our Docker images in this pipeline, but when building them
      # for testing, let's use the nightly tag.
      dockerTag: nightly
  snap_packaging_jobs:
    name: Snap packaging
    uses: "./.github/workflows/snap_packaging_jobs.yml"
    with:
      snapBuildTimeout: 5400
    secrets:
      LAUNCHPAD_CREDENTIALS: "${{ secrets.LAUNCHPAD_CREDENTIALS }}"
