# Nightly pipeline running each day for main.
name: Nightly build
on:
  schedule:
  - cron: 30 4 * * *
  workflow_dispatch:

jobs:
  test_and_package_stage:
    name: Test and Package
    permissions:
      contents: read
    uses: "./.github/workflows/test_and_package_stage.yml"
    with:
      dockerTag: nightly
      snapBuildTimeout: 19800
    secrets: inherit
  changelog_stage:
    name: Create changelog
    permissions:
      contents: read
    uses: "./.github/workflows/changelog_stage.yml"
  nightly_deploy_stage:
    name: Nightly deploy
    permissions:
      contents: read
    needs: test_and_package_stage
    uses: "./.github/workflows/common_deploy_jobs.yml"
    secrets: inherit
    with:
      dockerTag: nightly
      snapReleaseChannel: edge
  re-run:
    needs:
    - test_and_package_stage
    - changelog_stage
    - nightly_deploy_stage
    if: failure() && fromJSON(github.run_attempt) < 3
    permissions:
      actions: write
      checks: write
    runs-on: ubuntu-latest
    steps:
      - env:
          GH_REPO: ${{ github.repository }}
          GH_TOKEN: ${{ github.token }}
          GH_DEBUG: api
        run: gh workflow run rerun.yml -F run_id=${{ github.run_id }}
