name: Snap packaging
on:
  workflow_call:
    inputs:
      snapBuildTimeout:
        description: 'timeout for snap builds in seconds'
        type: number
    secrets:
      LAUNCHPAD_CREDENTIALS:
        required: true

permissions:
  contents: read

env:
  SNAP_BUILD_TIMEOUT: ${{ inputs.snapBuildTimeout }}

jobs:

  generate_dns_list_matrix:
    name: List DNS package names
    runs-on: ubuntu-latest
    outputs:
      dns-dirs: ${{ steps.set-dns-dirs.outputs.dns-dirs }}
    steps:
    - name: checkout
      uses: actions/checkout@v6.0.2
      with:
        persist-credentials: false
    - id: set-dns-dirs
      run: |
        DNS_NAMES="$(echo certbot-dns-* | jq -R -s -c 'split(" ")[:-1]')"
        echo "dns-dirs=$DNS_NAMES" >> "$GITHUB_OUTPUT"
        echo $DNS_NAMES

