name: Test and package stage
on:
  workflow_call:
    inputs:
      dockerTag:
        description: 'docker tag to push to'
        type: string
      snapBuildTimeout:
        description: 'timeout for snap builds'
        type: number
permissions:
  contents: read

jobs:
  standard_tests_jobs:
    name: standard_tests_jobs
    uses: "./.github/workflows/standard_tests_jobs.yml"
  extended_tests_jobs:
    name: extended_tests_jobs
    uses: "./.github/workflows/extended_tests_jobs.yml"
    secrets: inherit
  packaging_jobs:
    name: packaging_jobs
    uses: "./.github/workflows/packaging_jobs.yml"
    with:
      dockerTag: ${{ inputs.dockerTag }}
      snapBuildTimeout: ${{ inputs.snapBuildTimeout }}
    secrets: inherit
