name: Test and package
on:
  workflow_call:
    inputs:
      dockerTag:
        description: 'docker tag to push to'
        type: string
      snapBuildTimeout:
        description: 'timeout for snap builds'
        type: number
permissions:
  contents: read

jobs:
  # standard_tests_jobs:
  #   name: Standard tests
  #   uses: "./.github/workflows/standard_tests_jobs.yml"
  # extended_tests_jobs:
  #   name: Extended tests
  #   uses: "./.github/workflows/extended_tests_jobs.yml"
  #   secrets: inherit
  docker_packaging_jobs:
    name: Docker packaging
    uses: "./.github/workflows/docker_packaging_jobs.yml"
    with:
      dockerTag: ${{ inputs.dockerTag }}
    secrets: inherit
  # snap_packaging_jobs:
  #   name: Snap packaging
  #   uses: "./.github/workflows/snap_packaging_jobs.yml"
  #   with:
  #     snapBuildTimeout: ${{ inputs.snapBuildTimeout }}
  #   secrets: inherit
